{% set name = "valis_wsi" %}
{% set version = "1.0.0rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/valis_wsi-{{ version }}.tar.gz
  sha256: a887a4b49f250eb656f26075d2720e63f753be1dcb14a7323d8b79d683a055d2

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  number: 0
  noarch: python

channel_priority: true

channels:
  - conda-forge
  - defaults

requirements:
  build:
    - libvips 
    - pip
    - python {{ python }}
    - setuptools
    - {{ compiler('c') }}

  host:
    - python >=3.7
    - libvips  
    - pip

  run:
    - python >=3.7
    - setuptools
    - beautifulsoup4
    # - bioformats_jar
    - scyjava
    - colorama
    - fastcluster
    - interpolation
    - joblib
    - jpype1
    - matplotlib-base
    - numba
    - numpy
    - ome-types
    - opencv
    - pandas
    - Pillow
    - pyvips
    - scikit-image
    - scikit-learn
    - scipy
    - Shapely
    - SimpleITK
    - tqdm
    - weightedstats
    - wheel
    - lxml
    - colour-science
    - libvips
    - maven

test:
  imports:
    - valis

about:
  home: https://github.com/MathOnco/valis
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Whole slide image (WSI) registration using rigid and non-rigid transformations. Transformations can be used to warp the WSI and/or points, e.g. cell positions. Registered WSI can be saved as ome.tiff images."

extra:
  recipe-maintainers:
    - Chandler Gatenbee
